---
- name: Print all extra vars and job info
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show all extra vars
      debug:
        var: vars

    - name: Print job_id if present
      debug:
        msg: "job_id: {{ job_id | default('not provided') }}"

    - name: Print job_name if present
      debug:
        msg: "job_name: {{ job_name | default('not provided') }}"
