apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: pizza-order
  title: Order Your Pizza
  description: Use this template to order a custom pizza
  namespace: default
  tags:
    - food
    - fun
spec:
  owner: PizzaLovers
  type: service

  parameters:
    - title: Pizza Details
      description: Provide details for your pizza order
      required:
        - token
        - pizzaSize
        - toppings
        - crustType
      properties:
        token:
          title: Token
          type: string
          description: Authentication token for order tracking
        pizzaSize:
          title: Pizza Size
          type: string
          description: Select the size of your pizza
          enum:
            - Small
            - Medium
            - Large
          default: Medium
        toppings:
          title: Toppings
          type: array
          items:
            type: string
            enum:
              - Pepperoni
              - Mushrooms
              - Onions
              - Sausage
              - Bacon
              - Extra Cheese
              - Black Olives
              - Green Peppers
              - Pineapple
              - Spinach
          uniqueItems: true
          ui:widget: checkboxes
        crustType:
          title: Crust Type
          type: string
          description: Select the type of crust
          enum:
            - Thin
            - Thick
            - Stuffed
          default: Thin
  steps:
    - id: validate-order
      name: Validate Order
      action: custom:validate-order
      input:
        token: ${{ parameters.token }}
        pizzaSize: ${{ parameters.pizzaSize }}
        toppings: ${{ parameters.toppings }}
        crustType: ${{ parameters.crustType }}
    - id: place-order
      name: Place Pizza Order
      action: custom:place-order
      input:
        token: ${{ parameters.token }}
        pizzaSize: ${{ parameters.pizzaSize }}
        toppings: ${{ parameters.toppings }}
        crustType: ${{ parameters.crustType }}
  output:
    text:
      - title: 'Pizza Order Placed Successfully'
        content: |
          **Pizza Size:** `${{ parameters.pizzaSize }}`
          **Toppings:** `${{ parameters.toppings }}`
          **Crust Type:** `${{ parameters.crustType }}`
    links:
      - title: Track Your Order
        url: ${{ steps['place-order'].output.trackingUrl }}
